# Git notes/key commands 

- [Pete's gist](https://gist.github.com/peterhurford/4d43aa5d6de114c0c741ba664c9c5ff5)

- [Hadley notes from 'packages' book](https://r-pkgs.org/git.html)

- I had notes on that ['Pro Git'](https://git-scm.com/book/en/v2) thing somewhere

## Favorite tips and commands (to try)

### Misc commands I might forget

`git rm` to stage deleted files.

### Branching 

Create a new branch with `git checkout -b <branch-name>.`

And then tell it there is a remote (? does this create the remote too?)
`git push --set-upstream origin <branch-name>`

`git branch` to list all branghes

Switch between branches with `git checkout <branch-name>`

Integrate 'meanwhile' work from master into branch:
`git merge master`

> Once you’re done working on a branch, merge it back into the master, then delete the branch:

```
git checkout master
git merge <branch-name>
git branch -d <branch-name>
```


### Merge conflicts

> I recommend starting by setting your merge conflict “style” to diff3. The diff3 style shows three things when you get a merge conflict: your local changes, the original file and the remote changes. The default style is diff2, which only shows your changes and the remote changes.

`git config --global merge.conflictstyle diff3`


### Commit messages:

> The first line of a commit message is called the subject line and should be brief (50 characters or less).

> Describe the why, not the what. Since you can always retrieve the diff associated with a commit, the message doesn’t need to say exactly what changed. Instead it should provide a high-level summary that focuses on the reasons for the change.


### Fixing stuff

> Navigate back in time until you find the commit where the mistake occurred. Write down the parent SHA: that’s the commit that occurred before the mistake so it will be good.

> See what the file looked like in the past so you can copy-and-paste the old code: git show <SHA> <filename>

> Or copy the version from the past back in to the present: git checkout <SHA> <filename>






### In Rstudio's git and other guis

> The background colours tells you whether the text has been added (green) or removed (red).

> a number in the first column identifies the old version, a number in second column identifies the new version.)

> In RStudio, staging and committing are done in the same place, the commit window, which you can open by clicking or by pressing Ctrl + Alt + m.






